// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3f4vvkKd189oYYx2cBeRYyGCt20G6KGc',
    appId: '1:906517384591:web:779a59346ae96f9b558ffa',
    messagingSenderId: '906517384591',
    projectId: 'reddit-clone-1ef6f',
    authDomain: 'reddit-clone-1ef6f.firebaseapp.com',
    storageBucket: 'reddit-clone-1ef6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiJTMzWovBU8_vtT9iY68pka9yKVgOSSI',
    appId: '1:906517384591:android:9ba6939d8fcc6a7f558ffa',
    messagingSenderId: '906517384591',
    projectId: 'reddit-clone-1ef6f',
    storageBucket: 'reddit-clone-1ef6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnOB8EQ6GVn6u_VgkYjdZDcT0uTfZZYmI',
    appId: '1:906517384591:ios:75a1b7e602653676558ffa',
    messagingSenderId: '906517384591',
    projectId: 'reddit-clone-1ef6f',
    storageBucket: 'reddit-clone-1ef6f.appspot.com',
    iosClientId:
        '906517384591-0g0is4v8fhb9qs0n166j5ampc0hkfabq.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
